# =================================================================
# unit
# =================================================================
unit: 
  # inch or mm
  length: "inch"

# =================================================================
# axis
# =================================================================
axis: 
  # number of axes: 5 or 6
  number: 5

# =================================================================
# speed
# =================================================================
default_speed:
  xyz: 100
  joint: 1000

# =================================================================
# jerk
# =================================================================
default_jerk:
  xyz: [50 , 50, 50, 300, 300, 300]
  joint: [300, 300, 300, 300, 300, 300] 


# =================================================================
# Calibration
# =================================================================
calibrate:
  j0: 0
  j1: 145
  j2: -90
  j3: 0
  j4: 0

# =================================================================
# Toolhead
# =================================================================
toolhead:
  # length of the toolhead is based on the unit
  x: 1.74

# =================================================================
# limit
# =================================================================
# all values are in deg
limit:
  # j0: [j0 minimum, j0 maximum]
  j0: [-175.0, 175.0]
  # j1: [j1 minimum, j1 maximum]
  j1: [-175.0, 160.0]
  # j2: [j2 minimum, j2 maximum]
  j2: [-130.0, 130.0]

# =================================================================
# Motion 
# =================================================================
motion:

  # Junction Integration Time
  # jt:0.01 Lower limit - probably will fail
  # jt:0.75 Good value for slower machines
  # jt:1.00 Nominal value
  # jt:1.20 Good value for fast machines
  # jt:5.00 Upper limit. Absolutely will fail 
  jt: 1

  # Path control mode
  # gpa: 0 Exact path mode, gpa:1 Exact stop mode, gpa:2 Continuous mode
  gpa: 2
  
  #Chordal tolerance in mm
  ct: 0.01   