# =================================================================
# speed
# =================================================================
default_speed:
  xyz: 100
  joint: 1000

# =================================================================
# jerk
# =================================================================
default_jerk:
  xyz: [50 , 50, 50, 100, 100, 100]
  joint: [300, 300, 300, 300, 300, 300] 


# =================================================================
# Calibration
# =================================================================
calibrate:
  j0: 0
  j1: 145
  j2: -90
  j3: 0
  j4: 0

# =================================================================
# Toolhead
# =================================================================
toolhead:
  # length of the toolhead in inch; default: 1.74
  x: 1.74

# =================================================================
# limit
# =================================================================
# all values are in deg
limit:
  # j0: [j0 minimum, j0 maximum]
  j0: [-175.0, 175.0]
  # j1: [j1 minimum, j1 maximum]
  j1: [-175.0, 160.0]
  # j2: [j2 minimum, j2 maximum]
  j2: [-130.0, 130.0]
